apiVersion: v1
kind: Service
metadata:
  name: postgres-dcm4che-service
  namespace: default
  labels:
    app: postgres-dcm4che
spec:
  ports:
  - name: postgres-dcm4che-port
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres-dcm4che
---